export interface AppEntry {
  name: string
  url: string
  description: string
  type: 'pm2' | 'docker' | 'external'
  stage: 'dev' | 'staging' | 'production'
  tunnelUrl: string
}

export const registeredApps: AppEntry[] = [
  {
    name: 'n8n',
    url: 'http://localhost:5678',
    tunnelUrl: 'https://n8n.example.com',
    description: 'Automação visual de workflows',
    type: 'docker',
    stage: 'production',
  },
  {
    name: 'Portainer',
    url: 'http://localhost:9000',
    tunnelUrl: 'http://localhost:9000',
    description: 'Gerenciamento de containers Docker',
    type: 'docker',
    stage: 'production',
  },
  {
    name: 'Vehicle Prospect',
    url: 'http://localhost:3002',
    tunnelUrl: 'https://prospect.example.com',
    description: 'Prospecção automotiva (Next.js/tRPC)',
    type: 'pm2',
    stage: 'production',
  },
  {
    name: 'ZapTickets',
    url: 'http://localhost:3000',
    tunnelUrl: 'https://ticket.example.com',
    description: 'Sistema de tickets WhatsApp',
    type: 'pm2',
    stage: 'production',
  },
  {
    name: 'GetSamurai',
    url: 'http://localhost:3001',
    tunnelUrl: 'https://samurai.example.com',
    description: 'Marketplace / ServiceHub',
    type: 'pm2',
    stage: 'production',
  },
  {
    name: 'Second Brain',
    url: 'http://localhost:3003',
    tunnelUrl: 'https://brain.example.com',
    description: 'Knowledge base / segunda mente',
    type: 'pm2',
    stage: 'production',
  },
  {
    name: 'Telemetria',
    url: 'http://localhost:8004',
    tunnelUrl: 'https://telemetria.example.com',
    description: 'Monitoramento e telemetria web',
    type: 'pm2',
    stage: 'production',
  },
  {
    name: 'TMS',
    url: 'http://localhost:8000',
    tunnelUrl: 'https://tms.example.com',
    description: 'Task Management System',
    type: 'pm2',
    stage: 'production',
  },
  {
    name: 'xCripto',
    url: 'http://localhost:8002',
    tunnelUrl: 'https://xcripto.example.com',
    description: 'Trading bot',
    type: 'pm2',
    stage: 'staging',
  },
  {
    name: 'Procedure Core',
    url: 'http://localhost:8014',
    tunnelUrl: 'https://procedimentos.example.com',
    description: 'Gestão de procedimentos',
    type: 'pm2',
    stage: 'production',
  },
  {
    name: 'OpenCode Web',
    url: 'http://localhost:4096',
    tunnelUrl: 'https://opencode.example.com',
    description: 'OpenCode interface web',
    type: 'pm2',
    stage: 'production',
  },
  {
    name: 'LabAgents (Front)',
    url: 'http://127.0.0.1:5180',
    tunnelUrl: 'http://127.0.0.1:5180',
    description: 'Plataforma multi-agente',
    type: 'pm2',
    stage: 'dev',
  },
  {
    name: 'LabAgents (WhatsApp)',
    url: 'http://localhost:3020',
    tunnelUrl: 'http://localhost:3020',
    description: 'Gateway WhatsApp LabAgents',
    type: 'pm2',
    stage: 'dev',
  },
  {
    name: 'ChatSSVS (Admin)',
    url: 'http://localhost:5173',
    tunnelUrl: 'http://localhost:5173',
    description: 'Painel admin ChatSSVS',
    type: 'pm2',
    stage: 'dev',
  },
  {
    name: 'SidneyBot v2',
    url: 'http://localhost:3007',
    tunnelUrl: 'http://localhost:3007',
    description: 'Bot WhatsApp evoluído',
    type: 'pm2',
    stage: 'production',
  },
  {
    name: 'Espetinho Agent',
    url: 'http://localhost:3006',
    tunnelUrl: 'http://localhost:3006',
    description: 'Agente especializado',
    type: 'pm2',
    stage: 'production',
  },
  {
    name: 'Transcribe Service',
    url: 'http://localhost:8003',
    tunnelUrl: 'http://localhost:8003',
    description: 'Serviço de transcrição de áudio',
    type: 'pm2',
    stage: 'production',
  },
  {
    name: 'n8n Webhook Relay',
    url: 'http://localhost:9001',
    tunnelUrl: 'https://n8n-hooks.example.com',
    description: 'Relay de webhooks n8n',
    type: 'pm2',
    stage: 'production',
  },
]
